[package]
name = "service"
version = "0.1.0"
edition = "2021"
description="Could not find crate on crates.io and could not import with git and path at the same time, so copied a version directly at https://github.com/graphprotocol/indexer/blob/972658b3ce8c512ad7b4dc575d29cd9d5377e3fe/packages/indexer-native/native"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native = { path = "../native" }
confy = "0.5.1"
ethers-core = "2.0.0"
ethers = "2.0.0"
ethers-contract = "2.0.0"
dotenvy = "0.15"
regex = "1.7.1"
log = "0.4.17"
anyhow = "1.0.57"
reqwest = "0.11.10"
async-trait = "0.1.53"
tokio = { version = "1", features = ["rt", "macros", "sync", "full"] }
tracing = "0.1.34"
thiserror = "1.0.30"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
axum = "0.5"
hyper = "0.14.27"
tower = { version = "0.4", features = ["util", "timeout"] }
tower-http = { version = "0.4.0", features = ["add-extension", "trace", "cors"] }
env_logger = "0.9.0"
toml = "0.7.4"
graphql-parser = "0.4.0"
lazy_static = "1.2.0"
once_cell = "1.17"
url = "2.3.1"
diesel = { version = "2.0", features = ["postgres", "serde_json", "numeric", "r2d2", "chrono"] }
diesel_derives = "2.0"
chrono = { version = "0.4", features = ["serde"] }
async-graphql = "4.0.16"
async-graphql-axum = "4.0.16"
bigdecimal = "0.3.0"
eip-712-derive = { git = "https://github.com/graphprotocol/eip-712-derive" }
libsecp256k1 = "0.7.0"
sha3 = "0.10.6"
secp256k1 = { version = "0.20", features = ["recovery"] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "ansi",
    "fmt",
    "std",
    "json",
] }
autometrics = { version = "0.3.3", features = ["prometheus-exporter"] }
clap = { version = "4.3.1", features = ["derive", "env"] }
metrics-exporter-prometheus = "0.11.0"
prometheus = "0.13.3"

# [[bin]]
# name = "indexer-native"
# path = "native"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
# Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
